version: '3'

services:
  web:
    build: .
    command:
      - sh
      - -c
      - |
        touch /app/logs/kaiten_api.log && \
        python manage.py migrate --noinput && \
        gunicorn LecapProject.wsgi:application \
          --bind 0.0.0.0:8000 \
          --workers 3 \
          --timeout 120
    expose:
      - "8000"
    volumes:
      - .:/app
    environment:
      DEBUG: "False"
      SECRET_KEY: "django-insecure-7-=c&xq%sv4nox#4)u_(w@z%zhk8$$m09*l7xn##-%%b645ous2"
    restart: always

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8000:8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
