# Generated by Django 5.1.7 on 2025-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LecapProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectrate',
            name='board_id',
            field=models.CharField(default=0, max_length=50, verbose_name='ID доски'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrate',
            name='board_title',
            field=models.CharField(default=0, max_length=200, verbose_name='Название доски'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectrate',
            unique_together={('project_id', 'board_id', 'role_id')},
        ),
    ]
