# Generated by Django 5.1.7 on 2025-04-14 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LecapProject', '0004_cleanup_rate_field_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultrolerate',
            name='last_sync',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обновление'),
        ),
    ]
