# Generated by Django 5.1.7 on 2025-04-14 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LecapProject', '0005_defaultrolerate_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrate',
            name='last_sync',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обновление'),
        ),
    ]
