# Generated by Django 5.1.7 on 2025-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),         
                ('billing_custom_field_id', models.CharField(max_length=100, verbose_name='ID кастомного поля Billing')),
                ('billing_custom_field_value_id', models.CharField(max_length=100, verbose_name='ID значения кастомного поля Billing')),
                ('api_auth_key', models.CharField(max_length=255, verbose_name='Ключ для авторизации в API')),
            ],
            options={
                'verbose_name': 'Настройка администратора',
                'verbose_name_plural': 'Настройки администратора',
            },
        ),
    ]
