# Generated by Django 5.1.7 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='  (Означает, что у пользователя есть все права без явного их назначения)', verbose_name='Суперпользователь'),
        ),
    ]
