# Generated by Django 5.1.7 on 2025-03-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='url_domain_value_id',
            field=models.CharField(default='', max_length=100, verbose_name='Доменное имя компании'),
            preserve_default=False,
        ),
    ]
