# Generated by Django 5.1.7 on 2025-06-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_override_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaitenUserRoleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaiten_user_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('override_role_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Роль в Kaiten')),
            ],
        ),
    ]
