# Generated by Django 5.1.7 on 2025-07-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_kaitenuserroleoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='project_custom_field_id',
            field=models.CharField(blank=True, help_text='ID кастомного поля “Проект” из Kaiten', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='override_role_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='-- Роль в Kaiten --'),
        ),
        migrations.AlterField(
            model_name='kaitenuserroleoverride',
            name='override_role_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='-- Роль в Kaiten --'),
        ),
    ]
