# Generated by Django 5.1.7 on 2025-04-01 16:15

import docxTemplate.models
import docxTemplate.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docxTemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefile',
            name='file',
            field=models.FileField(storage=docxTemplate.storage.CustomStorage(), upload_to=docxTemplate.models.template_upload_path),
        ),
    ]
